In [2]:
import numpy as np

# Section 1. N차원 배열 생성 
## 1-2. N차원 배열의 데이터 타입

In [6]:
arr = np.array([1,2,3], dtype=np.float)
print(arr, arr.dtype)

[1. 2. 3.] float64


<ipython-input-6-48adeed87b13>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([1,2,3], dtype=np.float)


In [8]:
arr = np.array([1.1 ,2.2 ,3.3 ], dtype=np.int)
print(arr, arr.dtype)

[1 2 3] int64


<ipython-input-8-d59259083fd6>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([1.1 ,2.2 ,3.3 ], dtype=np.int)


In [10]:
arr = np.array([0,1,1], dtype=np.bool)
print(arr, arr.dtype)

[False  True  True] bool


<ipython-input-10-0712b915f466>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([0,1,1], dtype=np.bool)


In [13]:
arr = np.array([0,1,2,3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)
# float32로 변환함 

[0 1 2 3] int64
[0. 1. 2. 3.] float32


In [22]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1,2,3,4, "64", "문자열"], dtype = int)
print(arr, arr.dtype)

ValueError: ignored